version: '3.8'
services:
  consumidor:
    image: nginx:latest
    volumes:
      - bucket:"/var/www/html/htdocs"
    
  s3:
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    privileged: true
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - AWS_S3_BUCKET=SEUBUCKET
        - AWS_S3_ACCESS_KEY_ID=SUA ACESS KEY
        - AWS_S3_SECRET_ACCESS_KEY=SUA SECRET ACCESS KEY
    devices:
      - /dev/fuse
    volumes:
      - bucket:/mnt/bucket
  

volumes:
  bucket: {}